<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class AuctionCatalogueSeeder extends Seeder
{
    public function run(): void
    {
        // ─────────────────────────────────────────────
        // 1.  UPCOMING AUCTION — 23rd June 2026
        // ─────────────────────────────────────────────
        $upcomingId = DB::table('auctions')->insertGetId([
            'title'               => '23rd June 2026 Auction',
            'slug'                => '23rd-june-2026-auction',
            'description'         => 'Our June 2026 auction features an exceptional selection of grand and upright pianos from world-class makers including Steinway, Yamaha, Kawai, Bechstein and more.',
            'banner_image'        => null,
            'catalogue_pdf'       => 'catalogues/june-2026-catalogue.pdf',
            'auction_type'        => 'online',
            'preview_start_time'  => Carbon::create(2026, 6, 19, 10, 0, 0),
            'start_time'          => Carbon::create(2026, 6, 23, 10, 0, 0),
            'end_time'            => Carbon::create(2026, 6, 23, 17, 0, 0),
            'status'              => 'published',
            'location'            => 'Piano Auctions Ltd, Bedford, UK',
            'is_featured'         => 1,
            'is_live'             => 0,
            'created_by'          => 1,
            'created_at'          => now(),
            'updated_at'          => now(),
        ]);

        $upcomingLots = [
            [
                'title'          => '– Petrof (c1997) Upright Piano – | Est. £800-£1,000',
                'slug'           => 'petrof-c1997-upright-piano-est-800-1000',
                'lot_number'     => 1,
                'description'    => 'A Model Sonatina upright piano in a modern satin mahogany case.',
                'brand'          => 'Petrof',
                'model'          => 'Sonatina',
                'serial_number'  => null,
                'year'           => 1997,
                'condition'      => 'Good',
                'piano_type'     => 'upright',
                'starting_bid'   => 800.00,
                'reserve_price'  => 800.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => 'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17879Jun26201-600x800.jpg',
                'gallery'        => json_encode([
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17879Jun26201.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17879Jun26202.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17879Jun26203.jpg',
                ]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– August Förster (c1975) Grand Piano – | Est. £1,000-£1,500',
                'slug'           => 'august-forster-c1975-grand-piano-est-1000-1500',
                'lot_number'     => 2,
                'description'    => 'A 6ft 3in (191cm) grand piano in a bright ebonised case on square tapered legs; together with a stool.',
                'brand'          => 'August Förster',
                'model'          => 'Grand',
                'serial_number'  => null,
                'year'           => 1975,
                'condition'      => 'Good',
                'piano_type'     => 'grand',
                'starting_bid'   => 1000.00,
                'reserve_price'  => 1000.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => 'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17890Jun26201-600x800.jpg',
                'gallery'        => json_encode([
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17890Jun26201.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17890Jun26202.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17890Jun26203.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17890Jun26204.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17890Jun26205.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17890Jun26206.jpg',
                ]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Yamaha (c1979) Upright Piano – | Est. £2,000-£2,500',
                'slug'           => 'yamaha-c1979-upright-piano-est-2000-2500',
                'lot_number'     => 3,
                'description'    => 'A Model U3 upright piano in a traditional bright ebonised case; together with a stool.',
                'brand'          => 'Yamaha',
                'model'          => 'U3',
                'serial_number'  => '17891',
                'year'           => 1979,
                'condition'      => 'Good',
                'piano_type'     => 'upright',
                'starting_bid'   => 2000.00,
                'reserve_price'  => 2000.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => 'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17891Jun26-600x624.jpg',
                'gallery'        => json_encode([
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17891Jun26.jpg',
                ]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Schimmel (c1991) Upright Piano – | Est. £1,800-£2,200',
                'slug'           => 'schimmel-c1991-upright-piano-est-1800-2200',
                'lot_number'     => 4,
                'description'    => 'A Model T130 upright piano in a traditional bright walnut case.',
                'brand'          => 'Schimmel',
                'model'          => 'T130',
                'serial_number'  => '17885',
                'year'           => 1991,
                'condition'      => 'Good',
                'piano_type'     => 'upright',
                'starting_bid'   => 1800.00,
                'reserve_price'  => 1800.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => 'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17885Jun26201-600x450.jpg',
                'gallery'        => json_encode([
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17885Jun26201.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17885Jun26202.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17885Jun26203.jpg',
                ]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Steinway (c1925) Grand Piano – | Est. £20,000-£25,000',
                'slug'           => 'steinway-c1925-grand-piano-est-20000-25000',
                'lot_number'     => 5,
                'description'    => 'A 6ft 2in (188cm) Model A grand piano in a bright ebonised case on square tapered legs. Fully restored and rebuilt by Steinway in 1999.',
                'brand'          => 'Steinway',
                'model'          => 'Model A',
                'serial_number'  => '17888',
                'year'           => 1925,
                'condition'      => 'Restored',
                'piano_type'     => 'grand',
                'starting_bid'   => 20000.00,
                'reserve_price'  => 20000.00,
                'current_bid'    => null,
                'bid_increment'  => 500.00,
                'featured_image' => 'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17888Jun26201.jpg',
                'gallery'        => json_encode([
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17888Jun26201.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17888Jun26202.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17888Jun26203.jpg',
                ]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Bechstein (c2000) Grand Piano – | Est. £10,000-£15,000',
                'slug'           => 'bechstein-c2000-grand-piano-est-10000-15000',
                'lot_number'     => 6,
                'description'    => 'A 5ft 11in (180cm) Model M grand piano in a bright mahogany case on square tapered legs.',
                'brand'          => 'Bechstein',
                'model'          => 'Model M',
                'serial_number'  => '17887',
                'year'           => 2000,
                'condition'      => 'Good',
                'piano_type'     => 'grand',
                'starting_bid'   => 10000.00,
                'reserve_price'  => 10000.00,
                'current_bid'    => null,
                'bid_increment'  => 250.00,
                'featured_image' => 'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17887Jun26201.jpg',
                'gallery'        => json_encode([
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17887Jun26201.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17887Jun26202.jpg',
                    'https://pianoauctions.co.uk/wp-content/uploads/2026/05/17887Jun26203.jpg',
                ]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Kawai (c2023) Upright Piano – | Est. £1,500-£2,000',
                'slug'           => 'kawai-c2023-upright-piano-est-1500-2000',
                'lot_number'     => 7,
                'description'    => 'A modern upright piano in an ebonised case, excellent condition.',
                'brand'          => 'Kawai',
                'model'          => 'K300',
                'serial_number'  => null,
                'year'           => 2023,
                'condition'      => 'Excellent',
                'piano_type'     => 'upright',
                'starting_bid'   => 1500.00,
                'reserve_price'  => 1500.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Yamaha (c1984) Upright Piano – | Est. £1,800-£2,200 Plus VAT',
                'slug'           => 'yamaha-c1984-upright-piano-est-1800-2200-plus-vat',
                'lot_number'     => 8,
                'description'    => 'A classic Yamaha upright piano in an ebonised case, well maintained.',
                'brand'          => 'Yamaha',
                'model'          => 'U1',
                'serial_number'  => null,
                'year'           => 1984,
                'condition'      => 'Good',
                'piano_type'     => 'upright',
                'starting_bid'   => 1800.00,
                'reserve_price'  => 1800.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Yamaha (c1979) Upright Piano – | Est. £1,800-£2,200 Plus VAT',
                'slug'           => 'yamaha-c1979-upright-piano-est-1800-2200-plus-vat',
                'lot_number'     => 9,
                'description'    => 'A Yamaha upright piano in a traditional ebonised case.',
                'brand'          => 'Yamaha',
                'model'          => 'U2',
                'serial_number'  => null,
                'year'           => 1979,
                'condition'      => 'Good',
                'piano_type'     => 'upright',
                'starting_bid'   => 1800.00,
                'reserve_price'  => 1800.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Kawai (c1973) Upright Piano – | Est. £800-£1,200 Plus VAT',
                'slug'           => 'kawai-c1973-upright-piano-est-800-1200-plus-vat',
                'lot_number'     => 10,
                'description'    => 'A vintage Kawai upright piano in a walnut case.',
                'brand'          => 'Kawai',
                'model'          => 'BS-2',
                'serial_number'  => null,
                'year'           => 1973,
                'condition'      => 'Fair',
                'piano_type'     => 'upright',
                'starting_bid'   => 800.00,
                'reserve_price'  => 800.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Bechstein (c1938) Grand Piano – | Est. £1,200-£1,800',
                'slug'           => 'bechstein-c1938-grand-piano-est-1200-1800',
                'lot_number'     => 11,
                'description'    => 'A pre-war Bechstein grand piano in an ebonised case.',
                'brand'          => 'Bechstein',
                'model'          => 'Grand',
                'serial_number'  => null,
                'year'           => 1938,
                'condition'      => 'Fair',
                'piano_type'     => 'grand',
                'starting_bid'   => 1200.00,
                'reserve_price'  => 1200.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Yamaha (c1977) Grand Piano – | Est. £2,500-£3,500',
                'slug'           => 'yamaha-c1977-grand-piano-est-2500-3500',
                'lot_number'     => 12,
                'description'    => 'A Yamaha grand piano in a bright ebonised case.',
                'brand'          => 'Yamaha',
                'model'          => 'G2',
                'serial_number'  => null,
                'year'           => 1977,
                'condition'      => 'Good',
                'piano_type'     => 'grand',
                'starting_bid'   => 2500.00,
                'reserve_price'  => 2500.00,
                'current_bid'    => null,
                'bid_increment'  => 100.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Yamaha (c1987) Grand Piano – | Est. £4,000-£6,000',
                'slug'           => 'yamaha-c1987-grand-piano-est-4000-6000',
                'lot_number'     => 13,
                'description'    => 'A Yamaha grand piano in an ebonised case on tapered legs.',
                'brand'          => 'Yamaha',
                'model'          => 'C3',
                'serial_number'  => null,
                'year'           => 1987,
                'condition'      => 'Good',
                'piano_type'     => 'grand',
                'starting_bid'   => 4000.00,
                'reserve_price'  => 4000.00,
                'current_bid'    => null,
                'bid_increment'  => 100.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Kawai (c1991) Grand Piano – | Est. £3,000-£5,000',
                'slug'           => 'kawai-c1991-grand-piano-est-3000-5000',
                'lot_number'     => 14,
                'description'    => 'A Kawai grand piano in a satin ebonised case.',
                'brand'          => 'Kawai',
                'model'          => 'KG-2',
                'serial_number'  => null,
                'year'           => 1991,
                'condition'      => 'Good',
                'piano_type'     => 'grand',
                'starting_bid'   => 3000.00,
                'reserve_price'  => 3000.00,
                'current_bid'    => null,
                'bid_increment'  => 100.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Bechstein (c1960) Grand Piano – | Est. £6,000-£8,000',
                'slug'           => 'bechstein-c1960-grand-piano-est-6000-8000',
                'lot_number'     => 15,
                'description'    => 'A Bechstein grand piano in a bright ebonised case.',
                'brand'          => 'Bechstein',
                'model'          => 'Model B',
                'serial_number'  => null,
                'year'           => 1960,
                'condition'      => 'Good',
                'piano_type'     => 'grand',
                'starting_bid'   => 6000.00,
                'reserve_price'  => 6000.00,
                'current_bid'    => null,
                'bid_increment'  => 250.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Steinway (c1884) Grand Piano – | Est. £15,000-£20,000',
                'slug'           => 'steinway-c1884-grand-piano-est-15000-20000',
                'lot_number'     => 16,
                'description'    => 'A rare Victorian-era Steinway grand piano, fully restored.',
                'brand'          => 'Steinway',
                'model'          => 'Model B',
                'serial_number'  => null,
                'year'           => 1884,
                'condition'      => 'Restored',
                'piano_type'     => 'grand',
                'starting_bid'   => 15000.00,
                'reserve_price'  => 15000.00,
                'current_bid'    => null,
                'bid_increment'  => 500.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Steinway (c1905) Grand Piano – | Est. £10,000-£15,000',
                'slug'           => 'steinway-c1905-grand-piano-est-10000-15000',
                'lot_number'     => 17,
                'description'    => 'An Edwardian Steinway grand piano in an ebonised case.',
                'brand'          => 'Steinway',
                'model'          => 'Model A',
                'serial_number'  => null,
                'year'           => 1905,
                'condition'      => 'Good',
                'piano_type'     => 'grand',
                'starting_bid'   => 10000.00,
                'reserve_price'  => 10000.00,
                'current_bid'    => null,
                'bid_increment'  => 250.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Liedermann Upright Piano – | Est. £1,200-£1,800 Plus VAT',
                'slug'           => 'liedermann-upright-piano-est-1200-1800-plus-vat',
                'lot_number'     => 18,
                'description'    => 'A Liedermann upright piano in a traditional walnut case.',
                'brand'          => 'Liedermann',
                'model'          => 'Upright',
                'serial_number'  => null,
                'year'           => null,
                'condition'      => 'Good',
                'piano_type'     => 'upright',
                'starting_bid'   => 1200.00,
                'reserve_price'  => 1200.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Yamaha (c2008) Upright Piano – | Est. £2,500-£3,500',
                'slug'           => 'yamaha-c2008-upright-piano-est-2500-3500',
                'lot_number'     => 19,
                'description'    => 'A modern Yamaha upright piano in a polished ebony case, excellent playing condition.',
                'brand'          => 'Yamaha',
                'model'          => 'U3',
                'serial_number'  => null,
                'year'           => 2008,
                'condition'      => 'Excellent',
                'piano_type'     => 'upright',
                'starting_bid'   => 2500.00,
                'reserve_price'  => 2500.00,
                'current_bid'    => null,
                'bid_increment'  => 100.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
            [
                'title'          => '– Steinmeyer Upright Piano – | Est. £300-£400',
                'slug'           => 'steinmeyer-upright-piano-est-300-400',
                'lot_number'     => 20,
                'description'    => 'A Steinmeyer upright piano in a traditional case, ideal for restoration.',
                'brand'          => 'Steinmeyer',
                'model'          => 'Upright',
                'serial_number'  => null,
                'year'           => null,
                'condition'      => 'Fair',
                'piano_type'     => 'upright',
                'starting_bid'   => 300.00,
                'reserve_price'  => 300.00,
                'current_bid'    => null,
                'bid_increment'  => 50.00,
                'featured_image' => null,
                'gallery'        => json_encode([]),
                'ends_at'        => Carbon::create(2026, 6, 23, 17, 0, 0),
                'status'         => 'published',
                'is_active'      => 1,
            ],
        ];

        foreach ($upcomingLots as $lot) {
            DB::table('lots')->insert(array_merge($lot, [
                'auction_id' => $upcomingId,
                'winner_id'          => null,
                'winning_bid_amount' => null,
                'sold_at'            => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ]));
        }

        // ─────────────────────────────────────────────
        // 2.  PAST AUCTIONS (5) WITH 5 LOTS EACH
        // ─────────────────────────────────────────────
        $pastAuctions = [
            [
                'auction' => [
                    'title'              => 'March 2026 Auction',
                    'slug'               => 'march-2026-auction',
                    'description'        => 'Our March 2026 auction featuring a superb range of grand and upright pianos.',
                    'banner_image'       => null,
                    'catalogue_pdf'      => 'catalogues/march-2026-catalogue.pdf',
                    'auction_type'       => 'online',
                    'preview_start_time' => Carbon::create(2026, 3, 16, 10, 0, 0),
                    'start_time'         => Carbon::create(2026, 3, 19, 10, 0, 0),
                    'end_time'           => Carbon::create(2026, 3, 19, 17, 0, 0),
                    'status'             => 'completed',
                    'location'           => 'Piano Auctions Ltd, Bedford, UK',
                    'is_featured'        => 0,
                    'is_live'            => 0,
                    'created_by'         => 1,
                ],
                'lots' => [
                    ['title' => '– Steinway (c1966) Grand Piano – | Est. £18,000-£22,000', 'slug' => 'steinway-c1966-grand-piano-mar-2026', 'lot_number' => 1, 'brand' => 'Steinway', 'model' => 'Model B', 'year' => 1966, 'piano_type' => 'grand', 'starting_bid' => 18000.00, 'reserve_price' => 18000.00, 'winning_bid_amount' => 21000.00, 'bid_increment' => 500.00, 'condition' => 'Good', 'description' => 'A superb Steinway Model B grand piano in ebonised case.', 'featured_image' => null],
                    ['title' => '– Yamaha (c1990) Grand Piano – | Est. £5,000-£7,000', 'slug' => 'yamaha-c1990-grand-piano-mar-2026', 'lot_number' => 2, 'brand' => 'Yamaha', 'model' => 'C2', 'year' => 1990, 'piano_type' => 'grand', 'starting_bid' => 5000.00, 'reserve_price' => 5000.00, 'winning_bid_amount' => 6200.00, 'bid_increment' => 100.00, 'condition' => 'Good', 'description' => 'A Yamaha C2 grand piano in polished ebony.', 'featured_image' => null],
                    ['title' => '– Kawai (c2005) Upright Piano – | Est. £2,000-£2,800', 'slug' => 'kawai-c2005-upright-piano-mar-2026', 'lot_number' => 3, 'brand' => 'Kawai', 'model' => 'K500', 'year' => 2005, 'piano_type' => 'upright', 'starting_bid' => 2000.00, 'reserve_price' => 2000.00, 'winning_bid_amount' => 2600.00, 'bid_increment' => 50.00, 'condition' => 'Excellent', 'description' => 'A modern Kawai upright in ebonised case.', 'featured_image' => null],
                    ['title' => '– Blüthner (c1930) Grand Piano – | Est. £4,000-£6,000', 'slug' => 'bluthner-c1930-grand-piano-mar-2026', 'lot_number' => 4, 'brand' => 'Blüthner', 'model' => 'Grand', 'year' => 1930, 'piano_type' => 'grand', 'starting_bid' => 4000.00, 'reserve_price' => 4000.00, 'winning_bid_amount' => 5500.00, 'bid_increment' => 100.00, 'condition' => 'Good', 'description' => 'A pre-war Blüthner grand in walnut case.', 'featured_image' => null],
                    ['title' => '– Bösendorfer (c1978) Grand Piano – | Est. £12,000-£16,000', 'slug' => 'bosendorfer-c1978-grand-piano-mar-2026', 'lot_number' => 5, 'brand' => 'Bösendorfer', 'model' => '200', 'year' => 1978, 'piano_type' => 'grand', 'starting_bid' => 12000.00, 'reserve_price' => 12000.00, 'winning_bid_amount' => 15500.00, 'bid_increment' => 500.00, 'condition' => 'Good', 'description' => 'A Bösendorfer 200 grand piano in ebonised case.', 'featured_image' => null],
                ],
            ],
            [
                'auction' => [
                    'title'              => 'January 2026 Auction',
                    'slug'               => 'january-2026-auction',
                    'description'        => 'Our January 2026 auction — a great selection of pianos to start the new year.',
                    'banner_image'       => null,
                    'catalogue_pdf'      => 'catalogues/january-2026-catalogue.pdf',
                    'auction_type'       => 'online',
                    'preview_start_time' => Carbon::create(2026, 1, 19, 10, 0, 0),
                    'start_time'         => Carbon::create(2026, 1, 22, 10, 0, 0),
                    'end_time'           => Carbon::create(2026, 1, 22, 17, 0, 0),
                    'status'             => 'completed',
                    'location'           => 'Piano Auctions Ltd, Bedford, UK',
                    'is_featured'        => 0,
                    'is_live'            => 0,
                    'created_by'         => 1,
                ],
                'lots' => [
                    ['title' => '– Yamaha (c2000) Grand Piano – | Est. £7,000-£9,000', 'slug' => 'yamaha-c2000-grand-piano-jan-2026', 'lot_number' => 1, 'brand' => 'Yamaha', 'model' => 'C3', 'year' => 2000, 'piano_type' => 'grand', 'starting_bid' => 7000.00, 'reserve_price' => 7000.00, 'winning_bid_amount' => 8500.00, 'bid_increment' => 250.00, 'condition' => 'Excellent', 'description' => 'A Yamaha C3 in polished ebony, superb condition.', 'featured_image' => null],
                    ['title' => '– Schimmel (c2003) Upright Piano – | Est. £3,000-£4,000', 'slug' => 'schimmel-c2003-upright-piano-jan-2026', 'lot_number' => 2, 'brand' => 'Schimmel', 'model' => 'C120', 'year' => 2003, 'piano_type' => 'upright', 'starting_bid' => 3000.00, 'reserve_price' => 3000.00, 'winning_bid_amount' => 3800.00, 'bid_increment' => 100.00, 'condition' => 'Good', 'description' => 'A Schimmel C120 upright in polished white.', 'featured_image' => null],
                    ['title' => '– Steinway (c1952) Grand Piano – | Est. £22,000-£28,000', 'slug' => 'steinway-c1952-grand-piano-jan-2026', 'lot_number' => 3, 'brand' => 'Steinway', 'model' => 'Model D', 'year' => 1952, 'piano_type' => 'grand', 'starting_bid' => 22000.00, 'reserve_price' => 22000.00, 'winning_bid_amount' => 27000.00, 'bid_increment' => 500.00, 'condition' => 'Restored', 'description' => 'A full concert grand Steinway Model D, fully restored.', 'featured_image' => null],
                    ['title' => '– Kawai (c1998) Upright Piano – | Est. £1,200-£1,600', 'slug' => 'kawai-c1998-upright-piano-jan-2026', 'lot_number' => 4, 'brand' => 'Kawai', 'model' => 'K200', 'year' => 1998, 'piano_type' => 'upright', 'starting_bid' => 1200.00, 'reserve_price' => 1200.00, 'winning_bid_amount' => 1550.00, 'bid_increment' => 50.00, 'condition' => 'Good', 'description' => 'A Kawai K200 upright in ebonised case.', 'featured_image' => null],
                    ['title' => '– Bechstein (c1975) Grand Piano – | Est. £8,000-£11,000', 'slug' => 'bechstein-c1975-grand-piano-jan-2026', 'lot_number' => 5, 'brand' => 'Bechstein', 'model' => 'Model C', 'year' => 1975, 'piano_type' => 'grand', 'starting_bid' => 8000.00, 'reserve_price' => 8000.00, 'winning_bid_amount' => 10200.00, 'bid_increment' => 250.00, 'condition' => 'Good', 'description' => 'A Bechstein Model C grand piano in ebonised case.', 'featured_image' => null],
                ],
            ],
            [
                'auction' => [
                    'title'              => 'November 2025 Auction',
                    'slug'               => 'november-2025-auction',
                    'description'        => 'Our November 2025 auction — an exceptional autumn sale.',
                    'banner_image'       => null,
                    'catalogue_pdf'      => 'catalogues/november-2025-catalogue.pdf',
                    'auction_type'       => 'online',
                    'preview_start_time' => Carbon::create(2025, 11, 17, 10, 0, 0),
                    'start_time'         => Carbon::create(2025, 11, 20, 10, 0, 0),
                    'end_time'           => Carbon::create(2025, 11, 20, 17, 0, 0),
                    'status'             => 'completed',
                    'location'           => 'Piano Auctions Ltd, Bedford, UK',
                    'is_featured'        => 0,
                    'is_live'            => 0,
                    'created_by'         => 1,
                ],
                'lots' => [
                    ['title' => '– Blüthner (c1898) Grand Piano – | Est. £6,000-£9,000', 'slug' => 'bluthner-c1898-grand-piano-nov-2025', 'lot_number' => 1, 'brand' => 'Blüthner', 'model' => 'Grand', 'year' => 1898, 'piano_type' => 'grand', 'starting_bid' => 6000.00, 'reserve_price' => 6000.00, 'winning_bid_amount' => 8200.00, 'bid_increment' => 250.00, 'condition' => 'Restored', 'description' => 'A Victorian Blüthner grand piano, beautifully restored.', 'featured_image' => null],
                    ['title' => '– Yamaha (c1995) Upright Piano – | Est. £1,500-£2,000', 'slug' => 'yamaha-c1995-upright-piano-nov-2025', 'lot_number' => 2, 'brand' => 'Yamaha', 'model' => 'U1', 'year' => 1995, 'piano_type' => 'upright', 'starting_bid' => 1500.00, 'reserve_price' => 1500.00, 'winning_bid_amount' => 1900.00, 'bid_increment' => 50.00, 'condition' => 'Good', 'description' => 'A Yamaha U1 upright in ebonised case.', 'featured_image' => null],
                    ['title' => '– Steinway (c1988) Grand Piano – | Est. £28,000-£35,000', 'slug' => 'steinway-c1988-grand-piano-nov-2025', 'lot_number' => 3, 'brand' => 'Steinway', 'model' => 'Model B', 'year' => 1988, 'piano_type' => 'grand', 'starting_bid' => 28000.00, 'reserve_price' => 28000.00, 'winning_bid_amount' => 34000.00, 'bid_increment' => 500.00, 'condition' => 'Excellent', 'description' => 'A Steinway Model B in superb condition.', 'featured_image' => null],
                    ['title' => '– Petrof (c2010) Upright Piano – | Est. £2,500-£3,500', 'slug' => 'petrof-c2010-upright-piano-nov-2025', 'lot_number' => 4, 'brand' => 'Petrof', 'model' => 'P125', 'year' => 2010, 'piano_type' => 'upright', 'starting_bid' => 2500.00, 'reserve_price' => 2500.00, 'winning_bid_amount' => 3200.00, 'bid_increment' => 100.00, 'condition' => 'Excellent', 'description' => 'A Petrof P125 upright in polished ebony.', 'featured_image' => null],
                    ['title' => '– Kawai (c2015) Grand Piano – | Est. £9,000-£12,000', 'slug' => 'kawai-c2015-grand-piano-nov-2025', 'lot_number' => 5, 'brand' => 'Kawai', 'model' => 'GX-2', 'year' => 2015, 'piano_type' => 'grand', 'starting_bid' => 9000.00, 'reserve_price' => 9000.00, 'winning_bid_amount' => 11500.00, 'bid_increment' => 250.00, 'condition' => 'Excellent', 'description' => 'A Kawai GX-2 grand piano in polished ebony.', 'featured_image' => null],
                ],
            ],
            [
                'auction' => [
                    'title'              => 'September 2025 Auction',
                    'slug'               => 'september-2025-auction',
                    'description'        => 'Our September 2025 auction — a fine late-summer selection.',
                    'banner_image'       => null,
                    'catalogue_pdf'      => 'catalogues/september-2025-catalogue.pdf',
                    'auction_type'       => 'online',
                    'preview_start_time' => Carbon::create(2025, 9, 15, 10, 0, 0),
                    'start_time'         => Carbon::create(2025, 9, 18, 10, 0, 0),
                    'end_time'           => Carbon::create(2025, 9, 18, 17, 0, 0),
                    'status'             => 'completed',
                    'location'           => 'Piano Auctions Ltd, Bedford, UK',
                    'is_featured'        => 0,
                    'is_live'            => 0,
                    'created_by'         => 1,
                ],
                'lots' => [
                    ['title' => '– Bösendorfer (c1990) Grand Piano – | Est. £18,000-£24,000', 'slug' => 'bosendorfer-c1990-grand-piano-sep-2025', 'lot_number' => 1, 'brand' => 'Bösendorfer', 'model' => '214', 'year' => 1990, 'piano_type' => 'grand', 'starting_bid' => 18000.00, 'reserve_price' => 18000.00, 'winning_bid_amount' => 23000.00, 'bid_increment' => 500.00, 'condition' => 'Good', 'description' => 'A Bösendorfer 214 grand piano in ebonised case.', 'featured_image' => null],
                    ['title' => '– Yamaha (c1988) Upright Piano – | Est. £2,000-£2,500', 'slug' => 'yamaha-c1988-upright-piano-sep-2025', 'lot_number' => 2, 'brand' => 'Yamaha', 'model' => 'U3', 'year' => 1988, 'piano_type' => 'upright', 'starting_bid' => 2000.00, 'reserve_price' => 2000.00, 'winning_bid_amount' => 2400.00, 'bid_increment' => 50.00, 'condition' => 'Good', 'description' => 'A Yamaha U3 upright in traditional ebonised case.', 'featured_image' => null],
                    ['title' => '– Steinway (c1910) Grand Piano – | Est. £14,000-£18,000', 'slug' => 'steinway-c1910-grand-piano-sep-2025', 'lot_number' => 3, 'brand' => 'Steinway', 'model' => 'Model O', 'year' => 1910, 'piano_type' => 'grand', 'starting_bid' => 14000.00, 'reserve_price' => 14000.00, 'winning_bid_amount' => 17500.00, 'bid_increment' => 500.00, 'condition' => 'Restored', 'description' => 'An Edwardian Steinway Model O, professionally restored.', 'featured_image' => null],
                    ['title' => '– Schimmel (c1999) Grand Piano – | Est. £7,000-£9,000', 'slug' => 'schimmel-c1999-grand-piano-sep-2025', 'lot_number' => 4, 'brand' => 'Schimmel', 'model' => 'C169', 'year' => 1999, 'piano_type' => 'grand', 'starting_bid' => 7000.00, 'reserve_price' => 7000.00, 'winning_bid_amount' => 8800.00, 'bid_increment' => 250.00, 'condition' => 'Good', 'description' => 'A Schimmel C169 grand piano in polished white.', 'featured_image' => null],
                    ['title' => '– Kawai (c2002) Upright Piano – | Est. £2,200-£2,800', 'slug' => 'kawai-c2002-upright-piano-sep-2025', 'lot_number' => 5, 'brand' => 'Kawai', 'model' => 'K400', 'year' => 2002, 'piano_type' => 'upright', 'starting_bid' => 2200.00, 'reserve_price' => 2200.00, 'winning_bid_amount' => 2700.00, 'bid_increment' => 100.00, 'condition' => 'Good', 'description' => 'A Kawai K400 upright in satin ebonised case.', 'featured_image' => null],
                ],
            ],
            [
                'auction' => [
                    'title'              => 'June 2025 Auction',
                    'slug'               => 'june-2025-auction',
                    'description'        => 'Our June 2025 auction — a fantastic summer collection.',
                    'banner_image'       => null,
                    'catalogue_pdf'      => 'catalogues/june-2025-catalogue.pdf',
                    'auction_type'       => 'online',
                    'preview_start_time' => Carbon::create(2025, 6, 16, 10, 0, 0),
                    'start_time'         => Carbon::create(2025, 6, 19, 10, 0, 0),
                    'end_time'           => Carbon::create(2025, 6, 19, 17, 0, 0),
                    'status'             => 'completed',
                    'location'           => 'Piano Auctions Ltd, Bedford, UK',
                    'is_featured'        => 0,
                    'is_live'            => 0,
                    'created_by'         => 1,
                ],
                'lots' => [
                    ['title' => '– Steinway (c1935) Grand Piano – | Est. £16,000-£20,000', 'slug' => 'steinway-c1935-grand-piano-jun-2025', 'lot_number' => 1, 'brand' => 'Steinway', 'model' => 'Model A', 'year' => 1935, 'piano_type' => 'grand', 'starting_bid' => 16000.00, 'reserve_price' => 16000.00, 'winning_bid_amount' => 19500.00, 'bid_increment' => 500.00, 'condition' => 'Good', 'description' => 'An Art Deco era Steinway Model A grand piano.', 'featured_image' => null],
                    ['title' => '– Yamaha (c2010) Grand Piano – | Est. £8,000-£11,000', 'slug' => 'yamaha-c2010-grand-piano-jun-2025', 'lot_number' => 2, 'brand' => 'Yamaha', 'model' => 'C2X', 'year' => 2010, 'piano_type' => 'grand', 'starting_bid' => 8000.00, 'reserve_price' => 8000.00, 'winning_bid_amount' => 10500.00, 'bid_increment' => 250.00, 'condition' => 'Excellent', 'description' => 'A Yamaha C2X grand piano in polished ebony.', 'featured_image' => null],
                    ['title' => '– Bechstein (c1920) Grand Piano – | Est. £5,000-£7,000', 'slug' => 'bechstein-c1920-grand-piano-jun-2025', 'lot_number' => 3, 'brand' => 'Bechstein', 'model' => 'Model A', 'year' => 1920, 'piano_type' => 'grand', 'starting_bid' => 5000.00, 'reserve_price' => 5000.00, 'winning_bid_amount' => 6800.00, 'bid_increment' => 250.00, 'condition' => 'Good', 'description' => 'A 1920s Bechstein grand piano in ebonised case.', 'featured_image' => null],
                    ['title' => '– Petrof (c2018) Upright Piano – | Est. £3,500-£4,500', 'slug' => 'petrof-c2018-upright-piano-jun-2025', 'lot_number' => 4, 'brand' => 'Petrof', 'model' => 'P131', 'year' => 2018, 'piano_type' => 'upright', 'starting_bid' => 3500.00, 'reserve_price' => 3500.00, 'winning_bid_amount' => 4300.00, 'bid_increment' => 100.00, 'condition' => 'Excellent', 'description' => 'A Petrof P131 upright in polished ebony.', 'featured_image' => null],
                    ['title' => '– Kawai (c1985) Upright Piano – | Est. £1,000-£1,500', 'slug' => 'kawai-c1985-upright-piano-jun-2025', 'lot_number' => 5, 'brand' => 'Kawai', 'model' => 'BL-61', 'year' => 1985, 'piano_type' => 'upright', 'starting_bid' => 1000.00, 'reserve_price' => 1000.00, 'winning_bid_amount' => 1400.00, 'bid_increment' => 50.00, 'condition' => 'Good', 'description' => 'A Kawai BL-61 upright in a traditional walnut case.', 'featured_image' => null],
                ],
            ],
        ];

        foreach ($pastAuctions as $entry) {
            $auctionId = DB::table('auctions')->insertGetId(array_merge($entry['auction'], [
                'created_at' => now(),
                'updated_at' => now(),
            ]));

            foreach ($entry['lots'] as $lot) {
                DB::table('lots')->insert(array_merge($lot, [
                    'auction_id'         => $auctionId,
                    'serial_number'      => $lot['serial_number'] ?? null,
                    'reserve_price'      => $lot['reserve_price'],
                    'current_bid'        => $lot['winning_bid_amount'],
                    'bid_increment'      => $lot['bid_increment'],
                    'gallery'            => json_encode([]),
                    'ends_at'            => $entry['auction']['end_time'],
                    'status'             => 'sold',
                    'is_active'          => 0,
                    'winner_id'          => null,
                    'winning_bid_amount' => $lot['winning_bid_amount'],
                    'sold_at'            => $entry['auction']['end_time'],
                    'created_at'         => now(),
                    'updated_at'         => now(),
                ]));
            }
        }
    }
}